### ISSUE TITLE
AzureSubscriptionExtensions.GetId throws null reference exception

### ISSUE THREAD

**Issue by Am018** [Azure/azure-powershell-common#108]
The [line at AzureSubscriptionExtensions](https://github.com/Azure/azure-powershell-common/blob/master/src/Authentication.Abstractions/Extensions/AzureSubscriptionExtensions.cs#L31) throws null reference exception when param subscription is null.

We are seeing an issue in powershell module because of that as reported by multiple customers at https://github.com/Azure/azure-powershell/issues/7406.

**Comment by MiYanni** [comment]
Created fix here: https://github.com/Azure/azure-powershell-common/pull/109

**Comment by MiYanni** [comment]
Fixed in: https://github.com/Azure/azure-powershell-common/pull/109
