### ISSUE TITLE
Normalize-Location doesn't return any value

### ISSUE THREAD

**Issue by number213** [Azure/azure-powershell-common#79]
`Normalize-Location` in [ScenarioTest's Common code](https://github.com/Azure/azure-powershell-common/blob/dev/src/ScenarioTest.ResourceManager/Common.ps1#L623) doesn't return modified location value back.

I've found only [one place](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/KeyVault/Commands.KeyVault.Test/Scripts/ControlPlane/KeyVaultManagementTests.ps1#L322) where this location is used and it doesn't throw an error because in both cases it returns null

```
Assert-AreEqual (Normalize-Location $vaultLocation) (Normalize-Location $v.Location)
```

Also I think `Normalize-Location` could be used in `Get-Location`. When `Get-Location` filters locations for resource type it compares strings directly

```
$location = $resourceTypes.Locations | Where-Object { $_ -eq $preferredLocation }
```

If `$preferredLocation` is like `westus` the comparison would fail because resource type's locations are in human-readable format (`West US`). Normalizing both parts of comparison would help to avoid this issue.

**Comment by MiYanni** [comment]
@number213 I also just checked. That function, `Normalize-Location`, is only called in that single test you mentioned. I'd opt to just remove it if it is causing confusion.

Instead, you can do this for your test:
```powershell
$location.ToLower() -replace '[^a-z0-9]'
```

Since `Get-Location` is used for testing, if the service returns `westus` when the test expects `West US`, that **should be flagged as a failure**. We don't want to change it to hide potential issues. Basically, `Get-Location` is unaware of what format, Name or DisplayName, is being used for the location.

However, I do agree that there could be an improvement here. Also, I didn't even know we had a location cmdlet until I just found this: http://www.sqlservercentral.com/blogs/bradleyschacht/2018/05/22/azure-powershell-list-data-center-locations/

**Comment by number213** [comment]
> Basically, Get-Location is unaware of what format, Name or DisplayName, is being used for the location.

Is it possible for Get-Location to remember what format prefferedLocation is, do agnostic search and return location in the same format the user passed it? Something like

```powershell
    param([string]$providerNamespace, [string]$resourceType, [string]$preferredLocation)
    $isDisplayName = $preferredLocation.IndexOf(" ") -ne -1;

    # ...

    $location = $resourceTypes.Locations | Where-Object { (Normalize-Location $_) -eq (Normalize-Location $preferredLocation) }
    if ($location -eq $null)
    {
        # ...
    }
    elseif($isDisplayName)
    {

        return $location
    }
    else
    {
        return $location.ToLower() -replace '[^a-z0-9]'
    }
```

That's my concert, `Get-Location` doesn't work with `Name` format

```
PS C:\Users\v-anevse> Get-Location "Microsoft.Network" "ExpressRouteCircuits" "centraluseuap"
East US
PS C:\Users\v-anevse> Get-Location "Microsoft.Network" "ExpressRouteCircuits" "Central US EUAP"
Central US EUAP
```

**Comment by MiYanni** [comment]
@number213 I'd rather add a switch paramter to `Get-Location`, such as `-UseCanonical`, which you specify when you want the *all lowercase, no spaces* version of the location. So, using your example:

```powershell
PS C:\Users\v-anevse> Get-Location "Microsoft.Network" "ExpressRouteCircuits" "centraluseuap" -UseCanonical
centraluseuap
PS C:\Users\v-anevse> Get-Location "Microsoft.Network" "ExpressRouteCircuits" "Central US EUAP"
Central US EUAP
```

That way, current implementations are not broken/changed. And, you can get the functionality you want (explicitly) out of it. How does that sound?

**Comment by number213** [comment]
@MiYanni sounds good
